on:
  push:
    branches:
      - dev
      - upgrades

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Stage build artifacts
        run: |
          git add -f .
          git status

      - name: Make commit message
        run: |
          git config --global user.name "GitHub Actions"
          git commit -m "Deployed build artifacts (`date '+%F %T %Z'`)" || true

      - name: Push build artifacts to gh-pages branch
        run: git push --force --set-upstream origin gh-pages
